from flask import Flask, render_template_string
from threading import Thread
import os
from pymongo import MongoClient
from dotenv import load_dotenv
import datetime

load_dotenv()

app = Flask('')

# MongoDB Connection
MONGO_URI = os.getenv("MONGO_URI")
if MONGO_URI:
    client = MongoClient(MONGO_URI)
    db = client["ocw_bot_db"]
    users_col = db["users"]
    reports_col = db["weekly_reports"]
else:
    db = None

# HTML Template
DASHBOARD_HTML = """
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OCW Bot Dashboard</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f0f2f5; color: #333; margin: 0; padding: 20px; }
        .container { max-width: 1000px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #f8f9fa; font-weight: 600; color: #555; }
        tr:hover { background-color: #f1f1f1; }
        .badge { display: inline-block; padding: 3px 8px; border-radius: 12px; font-size: 0.85em; background-color: #e1ecf4; color: #2c3e50; margin-right: 5px; }
        .grade-A { color: #27ae60; font-weight: bold; }
        .grade-F { color: #c0392b; }
        .footer { margin-top: 40px; text-align: center; color: #7f8c8d; font-size: 0.9em; }
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 OCW Bot Dashboard</h1>
        
        {% if error %}
            <div style="color: red; padding: 10px; background: #fee;">{{ error }}</div>
        {% endif %}

        <!-- Latest Weekly Report -->
        <h2>📅 最新週報 ({{ latest_report.range_str if latest_report else '尚無資料' }})</h2>
        {% if latest_report %}
            <table>
                <thead>
                    <tr>
                        <th>排名</th>
                        <th>姓名</th>
                        <th>分數</th>
                        <th>等級</th>
                        <th>互動 (💬/👍)</th>
                        <th>成就</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in latest_report.stats %}
                    <tr>
                        <td>
                            {% if user.rank == 1 %}🥇{% elif user.rank == 2 %}🥈{% elif user.rank == 3 %}🥉{% else %}{{ user.rank }}{% endif %}
                        </td>
                        <td>{{ user.name }}</td>
                        <td>{{ "%.1f"|format(user.percent_score) }}</td>
                        <td class="grade-{{ user.grade[0] }}">{{ user.grade }}</td>
                        <td>{{ user.message_count }} / {{ user.reaction_count }}</td>
                        <td>
                            {% for badge in user.achievements %}
                                <span class="badge">{{ badge }}</span>
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>目前沒有週報資料。</p>
        {% endif %}

        <!-- Bonus Points Leaderboard -->
        <h2>🌟 總加分排行榜 (Bonus Points)</h2>
        {% if bonus_users %}
            <table>
                <thead>
                    <tr>
                        <th>姓名</th>
                        <th>目前加分</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in bonus_users %}
                    <tr>
                        <td>{{ user.name }}</td>
                        <td>{{ user.bonus }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>目前沒有加分資料。</p>
        {% endif %}

        <div class="footer">
            Generated by OCW Bot v1.2.0 | <a href="/api/stats">API View</a>
        </div>
    </div>
</body>
</html>
"""

@app.route('/')
def dashboard():
    if db is None:
        return render_template_string(DASHBOARD_HTML, error="❌ 資料庫未連接 (請檢查 MONGO_URI)", latest_report=None, bonus_users=None)
    
    # Fetch Latest Report
    latest_report = reports_col.find_one(sort=[("year", -1), ("week", -1)])
    
    # Sort stats in report if exists
    if latest_report and "stats" in latest_report:
        latest_report["stats"] = sorted(latest_report["stats"], key=lambda x: x.get("rank", 999) if x.get("rank", 0) > 0 else 999)

    # Fetch Bonus Users (only those with bonus > 0)
    bonus_users = list(users_col.find({"bonus": {"$gt": 0}}).sort("bonus", -1))

    return render_template_string(DASHBOARD_HTML, latest_report=latest_report, bonus_users=bonus_users)

@app.route('/api/stats')
def api_stats():
    if db is None: return {"error": "No DB"}
    latest = reports_col.find_one(sort=[("year", -1), ("week", -1)], projection={"_id": 0})
    return latest if latest else {"message": "No data"}

def run():
    app.run(host='0.0.0.0', port=int(os.environ.get("PORT", 8080)))

def keep_alive():
    t = Thread(target=run)
    t.start()
