from flask import Flask, render_template_string
from threading import Thread
import os
from pymongo import MongoClient
from dotenv import load_dotenv
import datetime

load_dotenv()

app = Flask('')

# MongoDB Connection
MONGO_URI = os.getenv("MONGO_URI")
if MONGO_URI:
    client = MongoClient(MONGO_URI)
    db = client["ocw_bot_db"]
    users_col = db["users"]
    reports_col = db["weekly_reports"]
else:
    db = None

# HTML Template
DASHBOARD_HTML = """
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OCW Bot Dashboard</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f0f2f5; color: #333; margin: 0; padding: 20px; }
        .container { max-width: 1000px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #f8f9fa; font-weight: 600; color: #555; }
        tr:hover { background-color: #f1f1f1; }
        .badge { display: inline-block; padding: 3px 8px; border-radius: 12px; font-size: 0.85em; background-color: #e1ecf4; color: #2c3e50; margin-right: 5px; }
        .grade-A { color: #27ae60; font-weight: bold; }
        .grade-F { color: #c0392b; }
        .footer { margin-top: 40px; text-align: center; color: #7f8c8d; font-size: 0.9em; }
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 OCW Bot Dashboard</h1>
        
        {% if error %}
            <div style="color: red; padding: 10px; background: #fee;">{{ error }}</div>
        {% endif %}

        <!-- Latest Weekly Report -->
        <h2>📅 最新週報 ({{ latest_report.range_str if latest_report else '尚無資料' }})</h2>
        {% if latest_report %}
            <table>
                <thead>
                    <tr>
                        <th>排名</th>
                        <th>姓名</th>
                        <th>分數</th>
                        <th>等級</th>
                        <th>互動 (💬/👍)</th>
                        <th>成就</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in latest_report.stats %}
                    <tr>
                        <td>
                            {% if user.rank == 1 %}🥇{% elif user.rank == 2 %}🥈{% elif user.rank == 3 %}🥉{% else %}{{ user.rank }}{% endif %}
                        </td>
                        <td>{{ user.name }}</td>
                        <td>{{ "%.1f"|format(user.percent_score) }}</td>
                        <td class="grade-{{ user.grade[0] }}">{{ user.grade }}</td>
                        <td>{{ user.message_count }} / {{ user.reaction_count }}</td>
                        <td>
                            {% for badge in user.achievements %}
                                <span class="badge">{{ badge }}</span>
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>目前沒有週報資料。</p>
        {% endif %}

        <!-- Bonus Points Leaderboard -->
        <h2>🌟 總加分排行榜 (Bonus Points)</h2>
        {% if bonus_users %}
            <table>
                <thead>
                    <tr>
                        <th>姓名</th>
                        <th>目前加分</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in bonus_users %}
                    <tr>
                        <td>{{ user.name }}</td>
                        <td>{{ user.bonus }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>目前沒有加分資料。</p>
        {% endif %}

        <div class="footer">
            Generated by OCW Bot v1.2.2 | <a href="/trends">📈 趨勢圖</a> | <a href="/api/stats">API View</a>
        </div>
    </div>
</body>
</html>
"""

# Trends Chart HTML Template
TRENDS_HTML = """
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OCW Bot - 趨勢圖</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f0f2f5; color: #333; margin: 0; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        .controls { margin: 20px 0; padding: 15px; background: #f8f9fa; border-radius: 5px; }
        .controls label { margin-right: 15px; }
        .chart-wrapper { position: relative; height: 500px; margin-top: 20px; }
        .footer { margin-top: 40px; text-align: center; color: #7f8c8d; font-size: 0.9em; }
        a { color: #3498db; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="container">
        <h1>📈 學生得分趨勢圖</h1>
        
        {% if error %}
            <div style="color: red; padding: 10px; background: #fee;">{{ error }}</div>
        {% else %}
            <div class="controls">
                <strong>🔍 篩選學生：</strong><br><br>
                <label><input type="checkbox" id="select-all" checked> 全選/全不選</label><br><br>
                <div id="student-filters"></div>
            </div>
            <div class="chart-wrapper">
                <canvas id="trendsChart"></canvas>
            </div>
        {% endif %}

        <div class="footer">
            Generated by OCW Bot v1.2.2 | <a href="/">返回儀表板</a>
        </div>
    </div>

    <script>
        const chartData = {{ chart_data|safe }};
        const ctx = document.getElementById('trendsChart').getContext('2d');
        
        // 生成顏色
        const colors = [
            'rgb(255, 99, 132)', 'rgb(54, 162, 235)', 'rgb(255, 206, 86)',
            'rgb(75, 192, 192)', 'rgb(153, 102, 255)', 'rgb(255, 159, 64)',
            'rgb(199, 199, 199)', 'rgb(83, 102, 147)', 'rgb(144, 238, 144)',
            'rgb(255, 140, 0)', 'rgb(220, 20, 60)', 'rgb(64, 224, 208)'
        ];

        const chart = new Chart(ctx, {
            type: 'line',
            data: chartData,
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    title: {
                        display: true,
                        text: '學生每週得分趨勢',
                        font: { size: 18 }
                    },
                    legend: {
                        display: true,
                        position: 'top',
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        max: 100,
                        title: {
                            display: true,
                            text: '得分'
                        }
                    },
                    x: {
                        title: {
                            display: true,
                            text: '週次'
                        }
                    }
                }
            }
        });

        // 生成篩選器
        const filtersDiv = document.getElementById('student-filters');
        chartData.datasets.forEach((dataset, index) => {
            const label = document.createElement('label');
            label.style.marginRight = '15px';
            label.innerHTML = `<input type="checkbox" class="student-filter" data-index="${index}" checked> ${dataset.label}`;
            filtersDiv.appendChild(label);
        });

        // 全選/全不選
        document.getElementById('select-all').addEventListener('change', function() {
            const checkboxes = document.querySelectorAll('.student-filter');
            checkboxes.forEach(cb => {
                cb.checked = this.checked;
                chart.setDatasetVisibility(cb.dataset.index, this.checked);
            });
            chart.update();
        });

        // 個別篩選
        filtersDiv.addEventListener('change', function(e) {
            if (e.target.classList.contains('student-filter')) {
                const index = e.target.dataset.index;
                chart.setDatasetVisibility(index, e.target.checked);
                chart.update();
            }
        });
    </script>
</body>
</html>
"""

@app.route('/')
def dashboard():
    if db is None:
        return render_template_string(DASHBOARD_HTML, error="❌ 資料庫未連接 (請檢查 MONGO_URI)", latest_report=None, bonus_users=None)
    
    # Fetch Latest Report
    latest_report = reports_col.find_one(sort=[("year", -1), ("week", -1)])
    
    # Sort stats in report if exists
    if latest_report and "stats" in latest_report:
        latest_report["stats"] = sorted(latest_report["stats"], key=lambda x: x.get("rank", 999) if x.get("rank", 0) > 0 else 999)

    # Fetch Bonus Users (only those with bonus > 0)
    bonus_users = list(users_col.find({"bonus": {"$gt": 0}}).sort("bonus", -1))

    return render_template_string(DASHBOARD_HTML, latest_report=latest_report, bonus_users=bonus_users)

@app.route('/api/stats')
def api_stats():
    if db is None: return {"error": "No DB"}
    latest = reports_col.find_one(sort=[("year", -1), ("week", -1)], projection={"_id": 0})
    return latest if latest else {"message": "No data"}

@app.route('/trends')
def trends():
    if db is None:
        return render_template_string(TRENDS_HTML, error="❌ 資料庫未連接 (請檢查 MONGO_URI)", chart_data=None)
    
    try:
        # 查詢所有週報數據並排序
        all_reports = list(reports_col.find().sort([("year", 1), ("week", 1)]))
        
        if not all_reports:
            return render_template_string(TRENDS_HTML, error="❌ 尚無歷史數據，請稍候 Bot 自動計算", chart_data=None)
        
        # 整理數據
        labels = []  # Week labels
        students_data = {}  # {student_name: [scores]}
        
        for report in all_reports:
            week_label = f"Week {report['week']}"
            labels.append(week_label)
            
            for user_stat in report.get('stats', []):
                name = user_stat.get('name', 'Unknown')
                score = user_stat.get('percent_score', 0)
                
                if name not in students_data:
                    students_data[name] = []
                students_data[name].append(score)
        
        # 生成 Chart.js datasets
        colors = [
            'rgb(255, 99, 132)', 'rgb(54, 162, 235)', 'rgb(255, 206, 86)',
            'rgb(75, 192, 192)', 'rgb(153, 102, 255)', 'rgb(255, 159, 64)',
            'rgb(199, 199, 199)', 'rgb(83, 102, 147)', 'rgb(144, 238, 144)',
            'rgb(255, 140, 0)', 'rgb(220, 20, 60)', 'rgb(64, 224, 208)'
        ]
        
        datasets = []
        for idx, (name, scores) in enumerate(students_data.items()):
            # 補齊缺失週次的數據為 None (Chart.js 會跳過)
            full_scores = scores + [None] * (len(labels) - len(scores))
            
            datasets.append({
                'label': name,
                'data': full_scores,
                'borderColor': colors[idx % len(colors)],
                'backgroundColor': colors[idx % len(colors)].replace('rgb', 'rgba').replace(')', ', 0.1)'),
                'tension': 0.3,
                'fill': False
            })
        
        chart_data = {
            'labels': labels,
            'datasets': datasets
        }
        
        import json
        chart_data_json = json.dumps(chart_data)
        
        return render_template_string(TRENDS_HTML, chart_data=chart_data_json, error=None)
        
    except Exception as e:
        return render_template_string(TRENDS_HTML, error=f"❌ 載入數據時發生錯誤: {str(e)}", chart_data=None)

def run():
    app.run(host='0.0.0.0', port=int(os.environ.get("PORT", 8080)))

def keep_alive():
    t = Thread(target=run)
    t.start()
